name: eShopOnWeb Build and Test

#Triggers (uncomment line below to use it)
on: [push, workflow_dispatch]

jobs:
  #Build, test and publish .net web project in repository
  buildandtest:
    runs-on: ubuntu-latest
    steps:
    - name: Test with dotnet
      run: echo "Hello, there"
